// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyAssistant.Persistence;

#nullable disable

namespace MyAssistant.Persistence.Migrations
{
    [DbContext(typeof(MyAssistantDbContext))]
    partial class MyAssistantDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.6");

            modelBuilder.Entity("MyAssistant.Domain.Base.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("ActionTypeCode")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("TEXT");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EventDate")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EntityId");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("MyAssistant.Domain.Base.EntityShare", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("TEXT");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PermissionTypeCode")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("SharedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SharedWithUserId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PermissionTypeCode");

                    b.HasIndex("EntityId", "EntityType", "SharedWithUserId")
                        .IsUnique();

                    b.ToTable("entityShare");
                });

            modelBuilder.Entity("MyAssistant.Domain.Base.HistoryEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AuditLogId")
                        .HasColumnType("TEXT");

                    b.Property<string>("NewValue")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<string>("OldValue")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<string>("PropertyName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AuditLogId");

                    b.ToTable("historyEntry");
                });

            modelBuilder.Entity("MyAssistant.Domain.Lookups.AuditActionType", b =>
                {
                    b.Property<int>("Code")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Code");

                    b.ToTable("AuditActionTypes");

                    b.HasData(
                        new
                        {
                            Code = 1,
                            Description = "Create"
                        },
                        new
                        {
                            Code = 2,
                            Description = "Update"
                        },
                        new
                        {
                            Code = 3,
                            Description = "Delete"
                        });
                });

            modelBuilder.Entity("MyAssistant.Domain.Lookups.PermissionType", b =>
                {
                    b.Property<int>("Code")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Code");

                    b.ToTable("PermissionTypes");

                    b.HasData(
                        new
                        {
                            Code = 1,
                            Description = "Read"
                        },
                        new
                        {
                            Code = 2,
                            Description = "Read/Write"
                        },
                        new
                        {
                            Code = 3,
                            Description = "Read/Write/Delete"
                        });
                });

            modelBuilder.Entity("MyAssistant.Domain.Lookups.RecurrenceType", b =>
                {
                    b.Property<int>("Code")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Code");

                    b.ToTable("RecurrenceTypes");

                    b.HasData(
                        new
                        {
                            Code = 1,
                            Description = "None"
                        },
                        new
                        {
                            Code = 2,
                            Description = "Hourly"
                        },
                        new
                        {
                            Code = 3,
                            Description = "Daily"
                        },
                        new
                        {
                            Code = 4,
                            Description = "Weekly"
                        },
                        new
                        {
                            Code = 5,
                            Description = "Monthly"
                        },
                        new
                        {
                            Code = 6,
                            Description = "Annually"
                        });
                });

            modelBuilder.Entity("MyAssistant.Domain.Lookups.ShoppingItemActivityType", b =>
                {
                    b.Property<int>("Code")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Code");

                    b.ToTable("ShoppingItemActivityTypes");

                    b.HasData(
                        new
                        {
                            Code = 1,
                            Description = "Active"
                        },
                        new
                        {
                            Code = 2,
                            Description = "Inactive"
                        },
                        new
                        {
                            Code = 3,
                            Description = "Urgent"
                        },
                        new
                        {
                            Code = 4,
                            Description = "NotUrgent"
                        });
                });

            modelBuilder.Entity("MyAssistant.Domain.Models.BillingInfo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Amount")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsPaid")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ParentEntityId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ParentEntityType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("PayerId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ParentEntityId");

                    b.ToTable("BillingInfo");
                });

            modelBuilder.Entity("MyAssistant.Domain.Models.ChatMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AttachmentUrl")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsRead")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MessageType")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ReadAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ReceiverUserId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "ReceiverUserId", "SentAt");

                    b.ToTable("ChatMessages");
                });

            modelBuilder.Entity("MyAssistant.Domain.Models.Goal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAchieved")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("TargetDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Goals");
                });

            modelBuilder.Entity("MyAssistant.Domain.Models.Habit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("GoalId")
                        .HasColumnType("TEXT");

                    b.Property<int>("GoalValue")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsRecurring")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Progress")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("RecurrenceEndDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("RecurrenceTypeCode")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GoalId");

                    b.ToTable("Habits");
                });

            modelBuilder.Entity("MyAssistant.Domain.Models.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ActionUrl")
                        .HasMaxLength(400)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailNotification")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsRead")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Message")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ReadAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("MyAssistant.Domain.Models.ShoppingList", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ShoppingLists");
                });

            modelBuilder.Entity("MyAssistant.Domain.Models.ShoppingListItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsRecurring")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastPurchaseDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("RecurrenceEndDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("RecurrenceTypeCode")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ShoppingListId")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("TotalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ShoppingListId");

                    b.ToTable("ShoppingListItems");
                });

            modelBuilder.Entity("MyAssistant.Domain.Models.TaskItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("GoalId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsRecurring")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("RecurrenceEndDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("RecurrenceTypeCode")
                        .HasMaxLength(100)
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("Time")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GoalId");

                    b.ToTable("TaskItems");
                });

            modelBuilder.Entity("MyAssistant.Domain.Models.UserConnection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("FriendUserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("RequestSentDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("RequestStatus")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StatusMessage")
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "FriendUserId")
                        .IsUnique();

                    b.ToTable("UserConnections");
                });

            modelBuilder.Entity("MyAssistant.Domain.Base.AuditLog", b =>
                {
                    b.HasOne("MyAssistant.Domain.Models.BillingInfo", null)
                        .WithMany("AuditLogs")
                        .HasForeignKey("EntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyAssistant.Domain.Models.ChatMessage", null)
                        .WithMany("AuditLogs")
                        .HasForeignKey("EntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyAssistant.Domain.Models.Goal", null)
                        .WithMany("AuditLogs")
                        .HasForeignKey("EntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyAssistant.Domain.Models.Habit", null)
                        .WithMany("AuditLogs")
                        .HasForeignKey("EntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyAssistant.Domain.Models.Notification", null)
                        .WithMany("AuditLogs")
                        .HasForeignKey("EntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyAssistant.Domain.Models.ShoppingList", null)
                        .WithMany("AuditLogs")
                        .HasForeignKey("EntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyAssistant.Domain.Models.TaskItem", null)
                        .WithMany("AuditLogs")
                        .HasForeignKey("EntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyAssistant.Domain.Models.UserConnection", null)
                        .WithMany("AuditLogs")
                        .HasForeignKey("EntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MyAssistant.Domain.Base.EntityShare", b =>
                {
                    b.HasOne("MyAssistant.Domain.Models.BillingInfo", null)
                        .WithMany("Shares")
                        .HasForeignKey("EntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyAssistant.Domain.Models.Goal", null)
                        .WithMany("Shares")
                        .HasForeignKey("EntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyAssistant.Domain.Models.Habit", null)
                        .WithMany("Shares")
                        .HasForeignKey("EntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyAssistant.Domain.Models.ShoppingList", null)
                        .WithMany("Shares")
                        .HasForeignKey("EntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyAssistant.Domain.Models.TaskItem", null)
                        .WithMany("Shares")
                        .HasForeignKey("EntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyAssistant.Domain.Lookups.PermissionType", "PermissionType")
                        .WithMany()
                        .HasForeignKey("PermissionTypeCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PermissionType");
                });

            modelBuilder.Entity("MyAssistant.Domain.Base.HistoryEntry", b =>
                {
                    b.HasOne("MyAssistant.Domain.Base.AuditLog", "AuditLog")
                        .WithMany("HistoryEntries")
                        .HasForeignKey("AuditLogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AuditLog");
                });

            modelBuilder.Entity("MyAssistant.Domain.Models.BillingInfo", b =>
                {
                    b.HasOne("MyAssistant.Domain.Models.Goal", null)
                        .WithMany("Bills")
                        .HasForeignKey("ParentEntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyAssistant.Domain.Models.Habit", null)
                        .WithMany("Bills")
                        .HasForeignKey("ParentEntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyAssistant.Domain.Models.ShoppingList", null)
                        .WithMany("Bills")
                        .HasForeignKey("ParentEntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MyAssistant.Domain.Models.Habit", b =>
                {
                    b.HasOne("MyAssistant.Domain.Models.Goal", "LinkedGoal")
                        .WithMany("LinkedHabits")
                        .HasForeignKey("GoalId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("LinkedGoal");
                });

            modelBuilder.Entity("MyAssistant.Domain.Models.ShoppingListItem", b =>
                {
                    b.HasOne("MyAssistant.Domain.Models.ShoppingList", "ShoppingList")
                        .WithMany("Items")
                        .HasForeignKey("ShoppingListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ShoppingList");
                });

            modelBuilder.Entity("MyAssistant.Domain.Models.TaskItem", b =>
                {
                    b.HasOne("MyAssistant.Domain.Models.Goal", "LinkedGoal")
                        .WithMany("LinkedTasks")
                        .HasForeignKey("GoalId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("LinkedGoal");
                });

            modelBuilder.Entity("MyAssistant.Domain.Base.AuditLog", b =>
                {
                    b.Navigation("HistoryEntries");
                });

            modelBuilder.Entity("MyAssistant.Domain.Models.BillingInfo", b =>
                {
                    b.Navigation("AuditLogs");

                    b.Navigation("Shares");
                });

            modelBuilder.Entity("MyAssistant.Domain.Models.ChatMessage", b =>
                {
                    b.Navigation("AuditLogs");
                });

            modelBuilder.Entity("MyAssistant.Domain.Models.Goal", b =>
                {
                    b.Navigation("AuditLogs");

                    b.Navigation("Bills");

                    b.Navigation("LinkedHabits");

                    b.Navigation("LinkedTasks");

                    b.Navigation("Shares");
                });

            modelBuilder.Entity("MyAssistant.Domain.Models.Habit", b =>
                {
                    b.Navigation("AuditLogs");

                    b.Navigation("Bills");

                    b.Navigation("Shares");
                });

            modelBuilder.Entity("MyAssistant.Domain.Models.Notification", b =>
                {
                    b.Navigation("AuditLogs");
                });

            modelBuilder.Entity("MyAssistant.Domain.Models.ShoppingList", b =>
                {
                    b.Navigation("AuditLogs");

                    b.Navigation("Bills");

                    b.Navigation("Items");

                    b.Navigation("Shares");
                });

            modelBuilder.Entity("MyAssistant.Domain.Models.TaskItem", b =>
                {
                    b.Navigation("AuditLogs");

                    b.Navigation("Shares");
                });

            modelBuilder.Entity("MyAssistant.Domain.Models.UserConnection", b =>
                {
                    b.Navigation("AuditLogs");
                });
#pragma warning restore 612, 618
        }
    }
}
